Configure silent output capability for "grep" command.

diff --git a/man/configure b/man/configure
--- a/man/configure
+++ b/man/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS AWK CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S SET_MAKE CPP EGREP ALLOCA LIBOBJS man_config_file LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS AWK CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S SET_MAKE CPP EGREP ALLOCA LIBOBJS man_config_file NULLDEV man_grepsilent LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -6802,6 +6802,8 @@ if test "${with_config+set}" = set; then
 else
   man_config_file=${man_config_file_default-'man.conf'}
 fi;
+ echo "$as_me:$LINENO: checking where to install '${man_config_file}'" >&5
+echo $ECHO_N "checking where to install '${man_config_file}'... $ECHO_C" >&6
  if test `(dirname ${man_config_file}) 2>/dev/null ||
 $as_expr X${man_config_file} : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
 	 X${man_config_file} : 'X\(//\)[^/]' \| \
@@ -6846,6 +6848,74 @@ echo X"$ac_dir" |
    s?/*$??'`
  ;;
  esac
+ echo "$as_me:$LINENO: result: ${man_config_file}" >&5
+echo "${ECHO_T}${man_config_file}" >&6
+
+  echo "$as_me:$LINENO: checking name for NULL device" >&5
+echo $ECHO_N "checking name for NULL device... $ECHO_C" >&6
+ ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+ cat >conftest.$ac_ext <<_ACEOF
+
+   #if defined(_WIN32) || defined(__CYGWIN32__)
+    choke me
+   #endif
+
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  NULLDEV=/dev/null
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+NULLDEV=nul
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+ ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+ echo "$as_me:$LINENO: result: $NULLDEV" >&5
+echo "${ECHO_T}$NULLDEV" >&6
+
+
+ echo "$as_me:$LINENO: checking how to run grep silently" >&5
+echo $ECHO_N "checking how to run grep silently... $ECHO_C" >&6
+ man_grepsilent=">$NULLDEV 2>&1"
+ if test x$cross_compiling = xno; then
+   test x`echo testing | grep -q testing` = x && man_grepsilent=-q
+   test x`echo testing | grep -s testing` = x && man_grepsilent=-s
+ fi
+ echo "$as_me:$LINENO: result: grep $man_grepsilent" >&5
+echo "${ECHO_T}grep $man_grepsilent" >&6
+
 
 
             ac_config_files="$ac_config_files Makefile"
@@ -7492,6 +7562,8 @@ s,@EGREP@,$EGREP,;t t
 s,@ALLOCA@,$ALLOCA,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@man_config_file@,$man_config_file,;t t
+s,@NULLDEV@,$NULLDEV,;t t
+s,@man_grepsilent@,$man_grepsilent,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
 
